services:
  - type: web
    name: portfolio-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --timeout 120 --workers 1
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
