# Liste d'actifs populaires : (Nom affiché, Ticker)
STOCKS = [
    # Tech US
    ("Apple (AAPL)", "AAPL"),
    ("Microsoft (MSFT)", "MSFT"),
    ("NVIDIA (NVDA)", "NVDA"),
    ("Alphabet / Google (GOOGL)", "GOOGL"),
    ("Amazon (AMZN)", "AMZN"),
    ("Meta / Facebook (META)", "META"),
    ("Tesla (TSLA)", "TSLA"),
    ("Broadcom (AVGO)", "AVGO"),
    ("ASML (ASML)", "ASML"),
    ("Taiwan Semiconductor (TSM)", "TSM"),
    ("AMD (AMD)", "AMD"),
    ("Intel (INTC)", "INTC"),
    ("Salesforce (CRM)", "CRM"),
    ("Oracle (ORCL)", "ORCL"),
    ("Adobe (ADBE)", "ADBE"),
    ("Netflix (NFLX)", "NFLX"),
    ("Spotify (SPOT)", "SPOT"),
    ("Uber (UBER)", "UBER"),
    ("Airbnb (ABNB)", "ABNB"),
    ("Palantir (PLTR)", "PLTR"),
    ("Snowflake (SNOW)", "SNOW"),
    ("ServiceNow (NOW)", "NOW"),
    ("Cloudflare (NET)", "NET"),
    ("CrowdStrike (CRWD)", "CRWD"),
    ("Datadog (DDOG)", "DDOG"),
    ("Palo Alto Networks (PANW)", "PANW"),
    ("Qualcomm (QCOM)", "QCOM"),
    ("Texas Instruments (TXN)", "TXN"),
    ("Micron Technology (MU)", "MU"),
    ("IBM (IBM)", "IBM"),
    ("Cisco (CSCO)", "CSCO"),
    ("HP (HPQ)", "HPQ"),
    ("Dell (DELL)", "DELL"),
    ("Super Micro Computer (SMCI)", "SMCI"),

    # Finance US
    ("JPMorgan Chase (JPM)", "JPM"),
    ("Goldman Sachs (GS)", "GS"),
    ("Berkshire Hathaway (BRK-B)", "BRK-B"),
    ("Visa (V)", "V"),
    ("Mastercard (MA)", "MA"),
    ("Bank of America (BAC)", "BAC"),
    ("Morgan Stanley (MS)", "MS"),
    ("American Express (AXP)", "AXP"),
    ("BlackRock (BLK)", "BLK"),
    ("PayPal (PYPL)", "PYPL"),
    ("Coinbase (COIN)", "COIN"),
    ("Charles Schwab (SCHW)", "SCHW"),
    ("Citigroup (C)", "C"),
    ("Wells Fargo (WFC)", "WFC"),

    # Energie
    ("ExxonMobil (XOM)", "XOM"),
    ("Chevron (CVX)", "CVX"),
    ("Shell (SHEL)", "SHEL"),
    ("TotalEnergies (TTE)", "TTE"),
    ("ConocoPhillips (COP)", "COP"),
    ("NextEra Energy (NEE)", "NEE"),

    # Santé
    ("Johnson & Johnson (JNJ)", "JNJ"),
    ("Eli Lilly (LLY)", "LLY"),
    ("UnitedHealth (UNH)", "UNH"),
    ("Novo Nordisk (NVO)", "NVO"),
    ("Pfizer (PFE)", "PFE"),
    ("AbbVie (ABBV)", "ABBV"),
    ("Merck (MRK)", "MRK"),
    ("Thermo Fisher (TMO)", "TMO"),
    ("Intuitive Surgical (ISRG)", "ISRG"),
    ("Moderna (MRNA)", "MRNA"),
    ("Amgen (AMGN)", "AMGN"),
    ("AstraZeneca (AZN)", "AZN"),
    ("Sanofi (SNY)", "SNY"),
    ("CVS Health (CVS)", "CVS"),

    # Consommation
    ("Walmart (WMT)", "WMT"),
    ("Costco (COST)", "COST"),
    ("Nike (NKE)", "NKE"),
    ("McDonald's (MCD)", "MCD"),
    ("Starbucks (SBUX)", "SBUX"),
    ("Coca-Cola (KO)", "KO"),
    ("PepsiCo (PEP)", "PEP"),
    ("Procter & Gamble (PG)", "PG"),
    ("LVMH (LVMHF)", "LVMHF"),
    ("Hermès (HESAY)", "HESAY"),
    ("L'Oréal (LRLCY)", "LRLCY"),

    # Industrie / Aéro / Défense
    ("Boeing (BA)", "BA"),
    ("Airbus (EADSY)", "EADSY"),
    ("Caterpillar (CAT)", "CAT"),
    ("Deere & Company (DE)", "DE"),
    ("Lockheed Martin (LMT)", "LMT"),
    ("RTX Corporation (RTX)", "RTX"),
    ("General Electric (GE)", "GE"),
    ("Honeywell (HON)", "HON"),

    # Immobilier / REIT
    ("American Tower (AMT)", "AMT"),
    ("Prologis (PLD)", "PLD"),
    ("Simon Property (SPG)", "SPG"),

    # ETF populaires
    ("S&P 500 ETF - Vanguard (VOO)", "VOO"),
    ("S&P 500 ETF - SPDR (SPY)", "SPY"),
    ("Nasdaq 100 ETF (QQQ)", "QQQ"),
    ("Total Market ETF (VTI)", "VTI"),
    ("International ETF (VXUS)", "VXUS"),
    ("Emerging Markets ETF (EEM)", "EEM"),
    ("Obligations US (AGG)", "AGG"),
    ("Obligations Long Terme (TLT)", "TLT"),
    ("Or (GLD)", "GLD"),
    ("Argent (SLV)", "SLV"),
    ("Pétrole (USO)", "USO"),
    ("REIT ETF (VNQ)", "VNQ"),
    ("Small Cap ETF (IWM)", "IWM"),
    ("Dividendes ETF (VYM)", "VYM"),
    ("Europe ETF (VGK)", "VGK"),
    ("Japon ETF (EWJ)", "EWJ"),
    ("Chine ETF (FXI)", "FXI"),
    ("Inde ETF (INDA)", "INDA"),

    # Crypto (via Yahoo Finance)
    ("Bitcoin (BTC-USD)", "BTC-USD"),
    ("Ethereum (ETH-USD)", "ETH-USD"),
    ("Solana (SOL-USD)", "SOL-USD"),
    ("BNB (BNB-USD)", "BNB-USD"),
    ("XRP (XRP-USD)", "XRP-USD"),
]

STOCK_OPTIONS = [{"label": name, "value": ticker} for name, ticker in STOCKS]
